<?php
$projects =<<<EOF
CREATE TABLE PROJECTS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(30) NOT NULL,
    STATUS BOOLEAN NOT NULL
);
EOF;

$tasks =<<<EOF
CREATE TABLE TASKS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PROJECT_ID INTEGER NOT NULL,
    TASK_TYPE TEXT CHECK(TASK_TYPE IN ('t', 'h', 'd', 'b')) NOT NULL,
    STATUS INTEGER NOT NULL,
    TITLE VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    NOTE TEXT,
    TOTAL_TIME INTEGER DEFAULT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID) ON DELETE CASCADE
);
EOF;


$task_logs =<<<EOF
CREATE TABLE TASK_LOGS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TASK_ID INTEGER NOT NULL,
    NOTE TEXT,
    START_TIME TIMESTAMP DEFAULT NULL,
    END_TIME TIMESTAMP DEFAULT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (TASK_ID) REFERENCES TASKS(ID) ON DELETE CASCADE
);
EOF;
//STATUS : 0:pause, 1:start

?>
